/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pedrapapeltesoura;

import javax.swing.JOptionPane;

/**
 *
 * @author 182220019
 */
public class telaDoJogo extends javax.swing.JFrame {
int pedraj1, tesouraj1, papelj1, pedraj2, tesouraj2, papelj2;

    public telaDoJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabelTitulo = new javax.swing.JLabel();
        jbMostraGanhador = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rbtPedraJ1 = new javax.swing.JRadioButton();
        rbtPapelJ1 = new javax.swing.JRadioButton();
        rbtTesouraJ1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbtPedraJ2 = new javax.swing.JRadioButton();
        rbtPapelJ2 = new javax.swing.JRadioButton();
        rbtTesouraJ2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlabelTitulo.setText("Pedra Papel Tesoura");

        jbMostraGanhador.setText("Mostrar o Vencedor");
        jbMostraGanhador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostraGanhadorActionPerformed(evt);
            }
        });

        jLabel4.setText("Jogador 1:");

        rbtPedraJ1.setText("Pedra");
        rbtPedraJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPedraJ1ActionPerformed(evt);
            }
        });

        rbtPapelJ1.setText("Papel");
        rbtPapelJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPapelJ1ActionPerformed(evt);
            }
        });

        rbtTesouraJ1.setText("Tesoura");
        rbtTesouraJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTesouraJ1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Jogador 2:");

        rbtPedraJ2.setText("Pedra");
        rbtPedraJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPedraJ2ActionPerformed(evt);
            }
        });

        rbtPapelJ2.setText("Papel");
        rbtPapelJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPapelJ2ActionPerformed(evt);
            }
        });

        rbtTesouraJ2.setText("Tesoura");
        rbtTesouraJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTesouraJ2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtPedraJ2)
                                .addGap(18, 18, 18)
                                .addComponent(rbtPapelJ2)
                                .addGap(18, 18, 18)
                                .addComponent(rbtTesouraJ2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtPedraJ1)
                                .addGap(18, 18, 18)
                                .addComponent(rbtPapelJ1)
                                .addGap(18, 18, 18)
                                .addComponent(rbtTesouraJ1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jlabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jbMostraGanhador)))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbtPedraJ1)
                    .addComponent(rbtPapelJ1)
                    .addComponent(rbtTesouraJ1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbtPedraJ2)
                    .addComponent(rbtPapelJ2)
                    .addComponent(rbtTesouraJ2))
                .addGap(27, 27, 27)
                .addComponent(jbMostraGanhador)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMostraGanhadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostraGanhadorActionPerformed
      if  (pedraj1.isSelected() && tesouraj2.isSelected() || 
                papelj1.isSelected() && pedraj2.isSelected() ||
                    tesouraj1.isSelected() && papelj2.isSelected()) {
        JoptionPane.showMessageDialog(this,"Jogador 1 venceu");
    else if
        (pedraj2.isSelected() && tesouraj1.isSelected() || 
                papelj1.isSelected() && pedraj2.isSelected() ||
                    tesouraj1.isSelected() && papelj2.isSelected())
                
        
                
            
        
                
}


    }//GEN-LAST:event_jbMostraGanhadorActionPerformed

    private void rbtPedraJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPedraJ1ActionPerformed
pedraj1 = 0;    
    }//GEN-LAST:event_rbtPedraJ1ActionPerformed

    private void rbtPapelJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPapelJ1ActionPerformed
papelj1 = 1;        // TODO add your handling code here:
    }//GEN-LAST:event_rbtPapelJ1ActionPerformed

    private void rbtTesouraJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTesouraJ1ActionPerformed
tesouraj1 = 2;        // TODO add your handling code here:
    }//GEN-LAST:event_rbtTesouraJ1ActionPerformed

    private void rbtPedraJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPedraJ2ActionPerformed
pedraj2 = 0;        // TODO add your handling code here:
    }//GEN-LAST:event_rbtPedraJ2ActionPerformed

    private void rbtPapelJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPapelJ2ActionPerformed
papelj2 = 1;        // TODO add your handling code here:
    }//GEN-LAST:event_rbtPapelJ2ActionPerformed

    private void rbtTesouraJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTesouraJ2ActionPerformed
 tesouraj2 = 2;
    }//GEN-LAST:event_rbtTesouraJ2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaDoJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbMostraGanhador;
    private javax.swing.JLabel jlabelTitulo;
    private javax.swing.JRadioButton rbtPapelJ1;
    private javax.swing.JRadioButton rbtPapelJ2;
    private javax.swing.JRadioButton rbtPedraJ1;
    private javax.swing.JRadioButton rbtPedraJ2;
    private javax.swing.JRadioButton rbtTesouraJ1;
    private javax.swing.JRadioButton rbtTesouraJ2;
    // End of variables declaration//GEN-END:variables
}
